# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: truckat-frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 7654
    targetPort: 7654
  type: LoadBalancer
