apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: truckat-node-redis-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: truckat-node-redis-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50