apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: truckat-redis-replica-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: truckat-redis-replica-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50