apiVersion: v1
kind: Service
metadata:
  name: truckat-node-redis-service
spec:
  selector:
    app: truckat-node-redis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer