apiVersion: v1
kind: Service
metadata:
  name: truckat-redis-replica-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: truckat-redis-replica
